---
title: "An Introduction to R"
subtitle: "Part 1: Getting Started"
output:
html_document:
theme: null
highlight: null
css: css/styles.css
runtime: shiny
---

# What is R? 

R is a popular statistical programming language, which offers an extensive toolbox for working with and analyzing data. 
It supports various ways to import data, which can then be analyzed or manipulated using either *base* functions which come with R
or alternatively functions from various community-generated libraries. 

R is open-source software, which might partly explain why it took of in the statistical community (and beyond), such that nowadays
one can find R packages to perform almost any imaginable task. I would argue that this is R's main selling point: Due to the enormous number of
researchers working with R, there are packages not only for creating basic summary statistics or running linear regressions, but it is quite 
likely that even for very exotic methods, there is probably an R package implementing them. 


